name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
      
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Run pipenv
        run: |
          pipenv requirements > requirements.txt
          pip install -r requirements.txt
          rm -rf requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format github  .
        continue-on-error: true
      - name: Static Analysis with Bandit
        run: |
          pip install bandit
          bandit -c bandit.yaml -ll -ii -r . -f json -o bandit-report.json
      - name: Upload Bandit Scan Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json


