name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
      
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Run pipenv
        run: |
          pipenv requirements > requirements.txt

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
