# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results-3.11
        path: junit/test-results.xml
        # Use always() to always run this step to publish test results when there are test failure
    - name: Security scan with bandit
      run: |
        bandit -c bandit.yaml -r .

    - name: Generate OpenAPI file
      run: python app/util.py

    - name: Upload openapi
      uses: actions/upload-artifact@v3
      with:
        name: openapi
        path: openapi.json

    - name: Generate HTML
      uses: openapi-generators/openapitools-generator-action@v1
      with:
        generator: html

    - name: Upload openapi html
      uses: actions/upload-artifact@v3
      with:
        name: html-client
        path: html-client

      # # Uses an external tool, openapitools-generator-action, to generate the client code.
      # # The 'openapirc.json' file is the following: { "packageName": "collector", "projectName": "collector" }
      # # and it lives inside the master branch of the repository. Command outputs a new folder called 
      # # 'python-client' with the relevant client code.
      # - name: Generate Python Client
      #   uses: triaxtec/openapitools-generator-action@v1.0.0
      #   with:
      #     generator: python
      #     openapi-file: openapi.yaml
      #     config-file: openapirc.json
  